arb-dir: lib/localization
template-arb-file: base_tools_en.arb
output-dir: lib/localization/
output-localization-file: base_tools_localizations.dart
synthetic-package: false
output-class: BaseToolsLocalizations